INSERT INTO USER VALUES(9999, 9999, 'TRUE', 'admin', 'ROLE_ADMIN', 'admin');
INSERT INTO AUTHORITIES VALUES(9999, 'ROLE_ADMIN', 'admin');
INSERT INTO PRODUCT VALUES(0,'instruments','new','A guitar rock and roll','Guns and Roses xD','GutarJonMonMoron', 1500, 'active', 1);
INSERT INTO PRODUCT VALUES(1,'records','new','A RECORD OF A SONG','RECORD GOLDEN','MIDLLEMING', 20, 'active', 100);
INSERT INTO PRODUCT VALUES(2,'instruments','new','a microphone','lmics','Microphone', 200, 'active', 51);




///// HAS PROLBES WITH TRANSIENT -
INSERT INTO USER VALUES(1, 1, 'TRUE', '1234', 'ROLE_USER', 'Sakerini');
INSERT INTO AUTHORITIES VALUES(1, 'ROLE_USER', 'Sakerini');
INSERT INTO CUSTOMER VALUES(1, 'test@test.mail', 'TestName', '+79854444444','TRUE', '1234','Sakerini', null, null, null);
INSERT INTO BILLING_ADDRESS VALUES(1, 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', null);
INSERT INTO CART VALUES(1, 0.0, 1);
INSERT INTO SHIPPING_ADDRESS VALUES(1, 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', null);
UPDATE CUSTOMER SET BILLING_ADDRESS_ID = 1 WHERE CUSTOMER_ID = 1;
UPDATE CUSTOMER SET SHIPPING_ADDRESS_ID = 1 WHERE CUSTOMER_ID = 1;
UPDATE CUSTOMER SET CART_ID = 1 WHERE CUSTOMER_ID = 1;
